version: '3'

services:
  backend:
    build: ./api
    container_name: backend
    ports:
      - '3000:3000'
  frontend:
    build: ./sys-stats
    container_name: frontend
    expose:
      - 80
  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - '80:80'
    volumes:
      - ./sys-stats/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - frontend
