apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
spec:
  selector:
    matchLabels:
      app: backend
  replicas: 2
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: 125943371674.dkr.ecr.us-east-1.amazonaws.com/dockerbackend
          ports:
            - containerPort: 5000
